### ISSUE TITLE
Update instructions for how to point atom to jing & RNG files inside neb

### ISSUE THREAD

**Issue by philschatz** [Connexions/cnxml#11]
Currently `README.rst` says to use `~/.neb/` to find `jing.jar` and `cnxml.rng` but the instructions should be updated to use wherever `neb` puts them

**Comment by pumazi** [comment]
- to get the location of ``jing.jar``:  ``python -c "import pkg_resources; print(pkg_resources.resource_filename('cnxml', 'cnxml/jing.jar'))"``
- to get the root location to the RNG files:  ``python -c "import pkg_resources; print(pkg_resources.resource_filename('cnxml', 'cnxml/xml'))"``

**Comment by pumazi** [comment]
@philschatz, what kind of update to the instructions do you want here? Has this been addressed by moving the configuration instructions to nebuchadnezzar?

**Comment by kerwinso** [comment]
Resolved with `neb --config-atom` feature or whatever it's called.
