### ISSUE TITLE
Batch: Atom schema needs to be updated to account for derived modules when validating

### ISSUE THREAD

**Issue by brittweinstein** [Connexions/cnxml#17]
When I (a CM) attempt to validate my content in Atom I receive the below errors due to the modules being derived:

##Test plan: 
Same as validating mdml. 
## Exit Criteria: 
Batch will support derived copies without Atom error and we should be able to successfully publish.

PR: https://github.com/Connexions/cnxml/pull/12 

Related Issue: https://github.com/Connexions/cnx-press/issues/135 

![Screen_Shot_2018-04-03_at_11.04.14_AM.png](https://images.zenhubusercontent.com/5a01faba8a75884b90866af7/cad33d46-a6d5-49a1-b9cd-abfc29406d4e)![Screen_Shot_2018-04-03_at_11.05.33_AM.png](https://images.zenhubusercontent.com/5a01faba8a75884b90866af7/acbafc29-149f-48bd-8255-d74e29720adb)![Screen_Shot_2018-07-28_at_1.03.16_PM.png](https://images.zenhubusercontent.com/5a01faba8a75884b90866af7/de4cc19e-eb83-400f-ac79-e01c8cc59252)

**Comment by pumazi** [comment]
Depending on how the product is installed, it's possible the `cnxml` dependency didn't upgrade. `pip3 install --upgrade nebuchadnezzar` should upgrade the dependency. If it doesn't we'll need to look into this a bit more.

**Comment by Bkblodget** [comment]
Atom is no longer throwing an error for the "derived-from" tag.
